spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://127.0.0.1:3306/market
    username: root
    password: '0000'

  jpa:
    database: mysql
    show-sql: true

---

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher



